-- MySQL Script generated by MySQL Workbench
-- Wed Dec 22 09:13:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Los_Santos_Custum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Los_Santos_Custum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Los_Santos_Custum` DEFAULT CHARACTER SET utf8 ;
USE `Los_Santos_Custum` ;

-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NULL,
  `PhoneNumber` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ZipCode` INT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Customers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Customers_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Locations_Customers1_idx` (`Customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Locations_Customers1`
    FOREIGN KEY (`Customers_id`)
    REFERENCES `Los_Santos_Custum`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `CreationDate` DATE NOT NULL,
  `Icon` BLOB(1024) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Promotions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Percentage` INT NULL,
  `ExpirationDate` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Chassis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Chassis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `SerieNumber` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `SerieNumber_UNIQUE` (`SerieNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Transmission` VARCHAR(45) NULL,
  `SpeedAcceleration` FLOAT NULL,
  `MaxSpeed` INT NULL,
  `Brands_id` INT NOT NULL,
  `Customers_id` INT NOT NULL,
  `Promotions_id` INT NULL,
  `Chassis_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Brands_id`, `Customers_id`, `Promotions_id`, `Chassis_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Cars_Brands1_idx` (`Brands_id` ASC) VISIBLE,
  INDEX `fk_Cars_Customers1_idx` (`Customers_id` ASC) VISIBLE,
  INDEX `fk_Cars_Promotions1_idx` (`Promotions_id` ASC) VISIBLE,
  INDEX `fk_Cars_Chassis1_idx` (`Chassis_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Brands1`
    FOREIGN KEY (`Brands_id`)
    REFERENCES `Los_Santos_Custum`.`Brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Customers1`
    FOREIGN KEY (`Customers_id`)
    REFERENCES `Los_Santos_Custum`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Promotions1`
    FOREIGN KEY (`Promotions_id`)
    REFERENCES `Los_Santos_Custum`.`Promotions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Chassis1`
    FOREIGN KEY (`Chassis_id`)
    REFERENCES `Los_Santos_Custum`.`Chassis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Sellers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `BirthDate` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Cars_has_Sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Cars_has_Sellers` (
  `Cars_id` INT NOT NULL,
  `Sellers_id` INT NOT NULL,
  PRIMARY KEY (`Cars_id`, `Sellers_id`),
  INDEX `fk_Cars_has_Sellers_Sellers1_idx` (`Sellers_id` ASC) VISIBLE,
  INDEX `fk_Cars_has_Sellers_Cars1_idx` (`Cars_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_has_Sellers_Cars1`
    FOREIGN KEY (`Cars_id`)
    REFERENCES `Los_Santos_Custum`.`Cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_has_Sellers_Sellers1`
    FOREIGN KEY (`Sellers_id`)
    REFERENCES `Los_Santos_Custum`.`Sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Categories_has_Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Categories_has_Cars` (
  `Categories_id` INT NOT NULL,
  `Cars_id` INT NOT NULL,
  `Cars_Brands_id` INT NOT NULL,
  `Cars_Customers_id` INT NOT NULL,
  PRIMARY KEY (`Categories_id`, `Cars_id`, `Cars_Brands_id`, `Cars_Customers_id`),
  INDEX `fk_Categories_has_Cars_Cars1_idx` (`Cars_id` ASC, `Cars_Brands_id` ASC, `Cars_Customers_id` ASC) VISIBLE,
  INDEX `fk_Categories_has_Cars_Categories1_idx` (`Categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_has_Cars_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `Los_Santos_Custum`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Cars_Cars1`
    FOREIGN KEY (`Cars_id` , `Cars_Brands_id` , `Cars_Customers_id`)
    REFERENCES `Los_Santos_Custum`.`Cars` (`id` , `Brands_id` , `Customers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Los_Santos_Custum`.`Cars_has_Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Los_Santos_Custum`.`Cars_has_Models` (
  `Cars_id` INT NOT NULL,
  `Cars_Brands_id` INT NOT NULL,
  `Cars_Customers_id` INT NOT NULL,
  `Cars_Promotions_id` INT NOT NULL,
  `Models_id` INT NOT NULL,
  PRIMARY KEY (`Cars_id`, `Cars_Brands_id`, `Cars_Customers_id`, `Cars_Promotions_id`, `Models_id`),
  INDEX `fk_Cars_has_Models_Models1_idx` (`Models_id` ASC) VISIBLE,
  INDEX `fk_Cars_has_Models_Cars1_idx` (`Cars_id` ASC, `Cars_Brands_id` ASC, `Cars_Customers_id` ASC, `Cars_Promotions_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_has_Models_Cars1`
    FOREIGN KEY (`Cars_id` , `Cars_Brands_id` , `Cars_Customers_id` , `Cars_Promotions_id`)
    REFERENCES `Los_Santos_Custum`.`Cars` (`id` , `Brands_id` , `Customers_id` , `Promotions_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_has_Models_Models1`
    FOREIGN KEY (`Models_id`)
    REFERENCES `Los_Santos_Custum`.`Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
